flashcard/flashcard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("study.urls")),
    
    path("user/", include("user.urls")),

    path("admin/", admin.site.urls),
]

flashcard/study/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView

app_name = "study"

urlpatterns = [
    path("login/", views.Login_SignUpClass.as_view(), name="dangnhap"),
    path("", RedirectView.as_view(url='login/', permanent=True)),
    path("logout/", views.logout_view, name="dangxuat"),

    path("home/", views.trangchu, name="trangchu"),
    path("my-flashcard", views.my_flashcard, name="my-flashcard"),
    path("flashcards-search", views.search_flashcards, name="timkiem-flashcard"),
    path("my-flashcard/<int:flashcard_id>/add-cards", views.create_cards_for_flashcard, name="them-cards-flashcard"),
    path("my-flashcard/<int:flashcard_id>/edit", views.edit_flashcard, name="sua-flashcard"),
    path("my-flashcard/<int:flashcard_id>/edit-clone", views.edit_clone_flashcard, name="sua-clone-flashcard"),


    path("flashcard/<int:flashcard_id>/", views.study_flashcard_view, name="thenho"),
    path("flashcard/<int:flashcard_id>/shuffle", views.shuffle_card_show, name="tron-the"),

    path("flashcard/<int:flashcard_id>/sort-abc", views.sort_tuvung_ABC, name="sapxep-tuvungABC"),
    path("flashcard/<int:flashcard_id>/sort-abc/shuffle", views.shuffle_card_show_sort_ABC, name="sapxep-tuvungABC-tron-the"),

    path("flashcard/<int:flashcard_id>/study", views.study_theghinho, name="the-ghi-nho"),
    path("flashcard/<int:flashcard_id>/study/shuffle", views.study_shuffle, name="the-ghi-nho-tron-the"),
    path("flashcard/<int:flashcard_id>/quiz", views.study_quiz, name="quiz"),
    path("flashcard/<int:flashcard_id>/test", views.study_kiemtra, name="kiem-tra"),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flashcard/user/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "user"

urlpatterns = [
    path('profile/', views.profile_user, name='hoso'),
]

flashcard/study/models.py
from django.db import models
from user.models import LearnerUser
from django.core.exceptions import ValidationError
# Create your models here.
class FlashCard(models.Model):
    user = models.ForeignKey(LearnerUser, on_delete=models.CASCADE, related_name='user_flashcard')
    title = models.CharField(max_length=100)
    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)
    def __str__(self):
        return str(self.id) + ' - ' + self.title
    
    def clean(self):
        if not self.user_id:
            raise ValidationError('Please select a user before creating a new flash card.')
    
    def word_count(self):
        return self.card_set.count()
    
class Card(models.Model):
    word = models.CharField(max_length=100)
    meaning = models.CharField(max_length=200)
    flash_card = models.ForeignKey(FlashCard, on_delete=models.CASCADE)

    def clean(self):
        if not self.flash_card_id:
            raise ValidationError('Bạn phải lưu hoặc chọn một bộ thẻ trước khi tạo các từ vựng mới.')
        

flashcard/study/forms.py
from .models import LearnerUser, FlashCard, Card
from django import forms
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Tên người dùng'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email'}))
    password1 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={'placeholder': 'Mật khẩu'}))
    password2 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={'placeholder': 'Xác nhận mật khẩu'}))

    class Meta:
        model = LearnerUser
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].validators = []    

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and LearnerUser.objects.filter(email=email).exists():
            raise forms.ValidationError('Email này đã được sử dụng!!!')
        return email

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        if LearnerUser.objects.filter(email=email).exists():
            raise forms.ValidationError('Email này đã được sử dụng!!!')
        return cleaned_data

class CardForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = ['word', 'meaning', 'flash_card']
        widgets = {
            'word': forms.TextInput(attrs={'placeholder': 'Từ vựng'}),
            'meaning': forms.TextInput(attrs={'placeholder': 'Định nghĩa'}),
            'flash_card': forms.HiddenInput()
        }

    def __init__(self, *args, **kwargs):
        flash_card = kwargs.pop('flash_card', None)
        super(CardForm, self).__init__(*args, **kwargs)
        if flash_card:
            self.fields['flash_card'].initial = flash_card
            self.fields['flash_card'].queryset = FlashCard.objects.filter(id=flash_card.id)

CardFormSet = forms.inlineformset_factory(FlashCard, Card, form=CardForm, extra=2, can_delete=False)

class FlashCardForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Đặt tên cho bộ FlashCard của bạn', 'class': 'form-control mr-3'})
    )
    user = forms.ModelChoiceField(
        queryset=LearnerUser.objects.all(),
        widget=forms.HiddenInput(),
        empty_label=None
    )

    class Meta:
        model = FlashCard
        fields = ['title', 'user']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(FlashCardForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['user'].initial = user
            self.fields['user'].queryset = LearnerUser.objects.filter(id=user.id)

class FlashCardFormUpdate(forms.ModelForm):
    class Meta:
        model = FlashCard
        fields = ['title']  # Chỉ cho phép cập nhật tiêu đề

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].label = "New Title"  # Đặt nhãn cho trường tiêu đề

class CardUpdateForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = ['word', 'meaning']  # Chỉ cho phép cập nhật từ và nghĩa
        widgets = {
            'word': forms.TextInput(attrs={'placeholder': 'Từ vựng',
                                           'name': "card_data['word']",}),
            'meaning': forms.TextInput(attrs={'placeholder': 'Định nghĩa',
                                              'name': "card_data['meaning']",}),
        }

flashcard/study/views.py
import json
from django.shortcuts import render, redirect, get_object_or_404
from .models import FlashCard, Card
from django.contrib.auth import authenticate, login
from django.views.generic import View
from django.contrib import messages
from django.contrib.auth import logout
from .models import FlashCard
from .forms import SignUpForm, FlashCardForm, FlashCardFormUpdate, CardUpdateForm
from random import shuffle
from django.contrib.auth.decorators import login_required


def dangnhap(request):
    return render(request, 'study/dangnhap.html')

class Login_SignUpClass(View):
    def get(self, request):
        form_signup = SignUpForm()
        return render(request, 'study/dangnhap.html', {'form_signup': form_signup})
    def post(self, request):
        if 'username' in request.POST:
            form_signup = SignUpForm(request.POST)
            if form_signup.is_valid():
                user = form_signup.save()
                login(request, user)
                print("dang ky thanh cong")
                return redirect('user:hoso')
            else:
                form_signup = SignUpForm()
                print("dang ky khong thanh cong")
                request.POST = {}
                messages.error(request, 'Thông tin đăng ký không đúng', extra_tags='signup')
                return self.get(request)
        else:    
            email = request.POST.get('email')
            password = request.POST.get('password')
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                print("dang nhap thanh cong")
                return trangchu(request)
            else:
                print("dang nhap khong thanh cong")
                request.POST = {}
                messages.error(request, 'Địa chỉ email hoặc mật khẩu không đúng', extra_tags='login')
                return self.get(request)



def trangchu(request):
    if request.user.is_authenticated:
        print("da dang nhap")
        flashcard_recent = FlashCard.objects.all().order_by('-time_update')[:12]
        context = {'flashcard_data_recent': flashcard_recent, 'user_login': request.user}
    else:
        print("chua dang nhap")
        context = {'user_login': None, 'flashcard_data_recent': None}
    
    return render(request, 'study/trangchu.html', context)

def logout_view(request):
    logout(request)
    return redirect('study:dangnhap')

def study_flashcard_view(request, flashcard_id):
    flashcard = get_object_or_404(FlashCard, id=flashcard_id)
    cards = flashcard.card_set.all()
    context = {
        'flashcard': flashcard,
        'cards': cards,
        'user_login': request.user,
        'cards_order': cards,
        'isSortABC': False,
        'isShuffle': False
    }
    return render(request, 'study/flashcard.html', context)

def sort_flashcard(request, sort):
    if sort == 'alphabet':
        flashcard = FlashCard.objects.order_by('title')
    elif sort == 'newest':
        flashcard = FlashCard.objects.order_by('-created_at')
    elif sort == 'oldest':
        flashcard = FlashCard.objects.order_by('created_at')
    else:
        flashcard = FlashCard.objects.all()
    context = {'flashcard_data': flashcard, 'user_login': request.user}
    return render(request, 'study/trangchu.html', context)

def sort_tuvung_ABC(request, flashcard_id):
    flashcard = get_object_or_404(FlashCard, id=flashcard_id)
    cards = flashcard.card_set.all()
    cards_order = flashcard.card_set.order_by('word')
    context = {
        'flashcard': flashcard,
        'cards': cards,
        'user_login': request.user,
        'cards_order': cards_order,
        'isSortABC': True,
        'isShuffle': False
    }
    return render(request, 'study/flashcard.html', context)

def shuffle_card_show(request, flashcard_id):
    flashcard = get_object_or_404(FlashCard, id=flashcard_id)
    cards = flashcard.card_set.all()
    cards_list = list(cards)
    shuffle(cards_list)
    context = {
        'flashcard': flashcard,
        'cards': cards_list,
        'user_login': request.user,
        'cards_order': cards,
        'isSortABC': False,
        'isShuffle': True
    } 
    
    return render(request, 'study/flashcard.html', context)

def shuffle_card_show_sort_ABC(request, flashcard_id):
    flashcard = get_object_or_404(FlashCard, id=flashcard_id)
    cards = flashcard.card_set.all()
    cards_order = flashcard.card_set.order_by('word')
    cards_list = list(cards)
    shuffle(cards_list)
    context = {
        'flashcard': flashcard,
        'cards': cards_list,
        'user_login': request.user,
        'cards_order': cards_order,
        'isSortABC': True,
        'isShuffle': True
    } 
    
    return render(request, 'study/flashcard.html', context)

def study_theghinho(request, flashcard_id):
    flashcard = get_object_or_404(FlashCard, id=flashcard_id)
    cards = flashcard.card_set.all()
    context = {
        'flashcard': flashcard,
        'cards': cards,
        'user_login': request.user,
    } 
    return render(request, 'study/mode/mode_study.html', context)

import random
def study_quiz(request, flashcard_id):
    flashcard = get_object_or_404(FlashCard, id=flashcard_id)
    cards_quiz = flashcard.card_set.all().order_by('?')[:10]

    question_ids = [card.id for card in cards_quiz]
    other_cards = Card.objects.filter(flash_card=flashcard).exclude(id__in=question_ids)
    questions = []
    for card in cards_quiz:
        question = {
            'word': card.word,
            'answers': [card.meaning],
            'correct_answer_index': 0
        }
        if len(other_cards) >= 3:
            # Lấy ngẫu nhiên 3 đáp án khác từ danh sách other_cards
            three_other_cards = random.sample(list(other_cards), 3)
            question['answers'].extend([other_answer.meaning for other_answer in three_other_cards])
        else:
            # Nếu số lượng other_cards không đủ, lấy tất cả các đáp án khác từ danh sách other_cards
            question['answers'].extend([other_card.meaning for other_card in other_cards])

        # Xáo trộn thứ tự của các đáp án
        random.shuffle(question['answers'])

        # Update correct_answer_index based on shuffled answers
        question['correct_answer_index'] = question['answers'].index(card.meaning)

        # Lưu câu hỏi vào danh sách các câu hỏi
        questions.append(question)
    context = {
        'flashcard': flashcard,
        'user_login': request.user,
        'questions': questions,
    } 
    return render(request, 'study/mode/mode_quiz.html', context)

def study_kiemtra(request, flashcard_id):
    flashcard = get_object_or_404(FlashCard, id=flashcard_id)
    cards_test_yesno = flashcard.card_set.all().order_by('?')[:10]
    question_yesno_ids = [card.id for card in cards_test_yesno]
    cards_test_quiz = Card.objects.filter(flash_card=flashcard).exclude(id__in=question_yesno_ids).order_by('?')[:10]
    
    question_ids = question_yesno_ids + [card.id for card in cards_test_quiz]
    other_cards = Card.objects.filter(flash_card=flashcard).exclude(id__in=question_ids)
    questions_yesno = []
    questions_quiz = []

    
    for card in cards_test_yesno:
        other_card_yn = random.sample(list(other_cards), 1)[0]
        stat_queston = random.choice(["yes", "no"])
        if stat_queston == "no":
            question = {
                'word': card.word,
                'meaning': other_card_yn.meaning,
                'correct_answer': 'no',
            }            
            questions_yesno.append(question)
        else:
            question = {
                'word': card.word,
                'meaning': card.meaning,
                'correct_answer': 'yes',
            }
            questions_yesno.append(question)
    
    for card in cards_test_quiz:
        question = {
            'word': card.word,
            'answers': [card.meaning],
            'correct_answer_index': 0
        }
        if len(other_cards) >= 3:
            # Lấy ngẫu nhiên 3 đáp án khác từ danh sách other_cards
            three_other_cards = random.sample(list(other_cards), 3)
            question['answers'].extend([other_answer.meaning for other_answer in three_other_cards])
        else:
            # Nếu số lượng other_cards không đủ, lấy tất cả các đáp án khác từ danh sách other_cards
            question['answers'].extend([other_card.meaning for other_card in other_cards])

        # Xáo trộn thứ tự của các đáp án
        random.shuffle(question['answers'])

        # Update correct_answer_index based on shuffled answers
        question['correct_answer_index'] = question['answers'].index(card.meaning)
        
        # Lưu câu hỏi vào danh sách các câu hỏi
        questions_quiz.append(question)


    context = {
        'flashcard': flashcard,
        'user_login': request.user,
        'questions_yesno': questions_yesno,
        'questions_quiz': questions_quiz,
    } 
    return render(request, 'study/mode/mode_test.html', context)

def study_shuffle(request, flashcard_id):
    flashcard = get_object_or_404(FlashCard, id=flashcard_id)
    cards = flashcard.card_set.all()
    cards_list = list(cards)
    shuffle(cards_list)
    context = {
        'flashcard': flashcard,
        'cards': cards_list,
        'user_login': request.user,
        'isShuffle': True
    } 
    return render(request, 'study/mode/mode_study.html', context)

def my_flashcard(request):
    user_flashcards = FlashCard.objects.filter(user=request.user)
    if request.method == 'POST':
        flashcard_form = FlashCardForm(request.POST, user=request.user)
        if flashcard_form.is_valid():
            flashcard = flashcard_form.save(commit=False)
            flashcard.user = request.user  # Gán người dùng hiện tại cho trường user
            flashcard.save()
            return redirect('study:them-cards-flashcard', flashcard_id=flashcard.id)
    else:

flashcard/templates/study/mode/mode_quiz.html
{% extends "study/navbar_study.html" %}

{% load static %}

{% block title%}Quiz: | DPFs{% endblock %}

{% block mycss %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'study/mode/css/mode_quiz.css' %}">
{% endblock %}

{% block navbar_title %}
    <div class="navbar-nav navStudy col-4 mx-auto" style="flex-direction: column;">
        <h2 style="color: aquamarine;">QUIZ</h2>
    </div>
{% endblock %}
{% block content %}
    <div class="container">
        <h2 class="d-flex align-content-between justify-content-center pb-4 pt-4">Hãy chọn thuật ngữ thích hợp cho các từ sau</h2>
        {% for ques in questions %}
        <article class="questionLayout">
            <div class="questionQes">
                <div class="d-flex align-items-stretch">
                    <div style="font-size: 25px;font-family: Lucida Grande,Arial,sans-serif!important;">
                        {{forloop.counter}}.
                        {{ques.word}}
                    </div>
                </div>
            </div>
            <div class="questionAnswer">
                <h4>Chọn đáp án đúng</h4>
                <div class="boxAnswer" id="answer-{{forloop.counter}}">
                    {% for ans in ques.answers %}
                        <button class="boxContent">
                            <div class="numberAns">{{forloop.counter}}</div>
                            <div class="contentAns">
                                <div class="formattext">{{ans}}</div> 
                            </div>
                        </button>
                    {% endfor %}
                </div>
            </div>
            <div class="thong-bao-sai pt-5" style="display: none;">
                <h5 style="color: #b00020;">Chưa đúng, hãy cố gắng những câu tiếp theo nhé!</h5>
            </div>
            <div class="thong-bao-dung pt-5" style="display: none;">
                <h5 style="color: #30b748;">Rất tốt!Bạn đã trả lời đúng!!<3</h5>
            </div>
        </article>
        {% endfor %}
    </div>
    
{% endblock %}

{% block myjs %}
    {{ block.super }}
    <script>
        // Lắng nghe sự kiện khi nút đáp án được nhấn
        questions = {{questions|safe}};
        document.querySelectorAll('.boxContent').forEach(function(button) {
            button.addEventListener('click', function() {
                if (!this.classList.contains('selected')) {
                    // Lấy ID của nút đáp án được nhấn
                    var answerId = this.parentNode.getAttribute('id');
                    if (answerId) {
                        // Lấy số thứ tự của câu hỏi
                        var questionNumber = answerId.split('-')[1];
                        // Xác định đáp án đúng và lấy vị trí đáp án được chọn
                        var correctAnswerIndex = questions[questionNumber - 1].correct_answer_index + 1;
                        console.log(correctAnswerIndex);
                        var selectedAnswerIndex = parseInt(this.querySelector('.numberAns').innerText);
                        console.log(selectedAnswerIndex);
                        // Kiểm tra xem đáp án có đúng không
                        var isCorrect = (selectedAnswerIndex === correctAnswerIndex);
                        
                    
                        
                        // Tô viền màu xanh cho đáp án đúng
                        document.querySelectorAll('#answer-' + questionNumber + ' .numberAns').forEach(function(number) {
                            if (parseInt(number.textContent) === correctAnswerIndex) {
                            number.parentNode.style.border = '2px solid green';
                            }
                        });
                        
                        // Tô viền màu đỏ cho đáp án được chọn nếu sai
                        if (!isCorrect) {
                            this.style.border = '2px solid red';
                            this.parentNode.parentNode.parentNode.querySelector('.thong-bao-sai').style.display = 'block';
                        }
                        else {
                            this.parentNode.parentNode.parentNode.querySelector('.thong-bao-dung').style.display = 'block';
                        }
                        
                        // Thêm lớp 'selected' và vô hiệu hóa các nút đáp án
                        var allBoxContents = document.querySelectorAll('#answer-' + questionNumber + ' .boxContent');
                            for (var i = 0; i < allBoxContents.length; i++) {
                                allBoxContents[i].setAttribute('disabled', 'disabled');
                            }
                        this.classList.add('selected');
                        this.setAttribute('disabled', 'disabled');

                    }
                    
                }
            });
        });
    </script>
{% endblock %}

flashcard/templates/study/mode/mode_study.html
{% extends "study/navbar_study.html" %}

{% load static %}

{% block title%}Thẻ ghi nhớ: | DPFs{% endblock %}

{% block mycss %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'study/mode/css/mode.css' %}">
{% endblock %}

{% block content %}
    <main class="FlashcardShow" style="margin-top: 3.75rem;">
        <div class="Flashcard-studyPreview d-flex">
            <div id="flashcard-carousel" class="carousel slide">
                <div class="carousel-inner">
                    {% for card in cards %}                        
                        <div class="carousel-item{% if forloop.first %} active{% endif %}" data-index="{{ forloop.counter }}">
                            <div class="flip-card shadow-sm" style="height: 580px;"> 
                                <div class="face front">
                                    <div style="width: 70%;">
                                        <h3>{{ card.word }}</h3>
                                    </div>
                                </div>
                                <div class="face back">
                                    <div style="width: 70%;">
                                        <h3>{{ card.meaning }}</h3>                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <a class="carousel-control-prev" style="background-color: #b7d9db" href="#flashcard-carousel" role="button" data-bs-slide="prev" onclick="updateIndex(-1)">
                    <span class="carousel-control-prev-icon bg-red" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </a>
                <a class="carousel-control-next" style="background-color: #b7d9db" href="#flashcard-carousel" role="button" data-bs-slide="next" onclick="updateIndex(1)">
                    <span class="carousel-control-next-icon" aria-hidden="true" ></span>
                    <span class="visually-hidden">Next</span>
                </a>
            </div>
            <div class="underStudyPreview">
                <div class="d-flex gap-3" style="padding-top: 0.5rem;">
                    {% if isShuffle %}
                    <a href="{% url 'study:the-ghi-nho' flashcard_id=flashcard.id %}" type="button" id="btn-mix-card"><i class="fas fa-sync-alt fa-2x"></i></a>
                    {% else %}
                    <a href="{% url 'study:the-ghi-nho-tron-the' flashcard_id=flashcard.id %}" type="button" id="btn-mix-card"><i class="fas fa-sync-alt fa-2x"></i></a>
                    {% endif %}
                    <span id="describe-btn-mix">Trộn thẻ đang TẮT</span> 
                </div>
            </div>   
        </div>
    </main>
{% endblock %}

{% block myjs %}
    {{ block.super }}
    <script src="{% static 'study/mode/js/mode_study.js' %}"></script>
    <script>
        var countWordValue = {{ flashcard.word_count }};
        function updateIndex(change) {
            const activeItem = document.querySelector('.carousel-item.active');
            var indexcard = activeItem.getAttribute('data-index');
            
            indexcard = parseInt(indexcard)+change;
            if (indexcard == 0) {
                indexcard = countWordValue;
            }
            if (indexcard == countWordValue+1) {
                indexcard = 1;
            }
            const cardCounter = document.getElementById('card-counter-id');
            cardCounter.textContent = indexcard + '/' + countWordValue;
        };
    </script>
{% endblock %}