flashcard/flashcard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("study.urls")),
    
    path("user/", include("user.urls")),

    path("admin/", admin.site.urls),
]

flashcard/study/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView

app_name = "study"

urlpatterns = [
    path("login/", views.Login_SignUpClass.as_view(), name="dangnhap"),
    path("", RedirectView.as_view(url='login/', permanent=True)),
    path("logout/", views.logout_view, name="dangxuat"),

    path("home/", views.trangchu, name="trangchu"),
    path("my-flashcard", views.my_flashcard, name="my-flashcard"),
    path("flashcards-search", views.search_flashcards, name="timkiem-flashcard"),
    path("my-flashcard/<int:flashcard_id>/add-cards", views.create_cards_for_flashcard, name="them-cards-flashcard"),
    path("my-flashcard/<int:flashcard_id>/edit", views.edit_flashcard, name="sua-flashcard"),
    path("my-flashcard/<int:flashcard_id>/edit-clone", views.edit_clone_flashcard, name="sua-clone-flashcard"),


    path("flashcard/<int:flashcard_id>/", views.study_flashcard_view, name="thenho"),
    path("flashcard/<int:flashcard_id>/shuffle", views.shuffle_card_show, name="tron-the"),

    path("flashcard/<int:flashcard_id>/sort-abc", views.sort_tuvung_ABC, name="sapxep-tuvungABC"),
    path("flashcard/<int:flashcard_id>/sort-abc/shuffle", views.shuffle_card_show_sort_ABC, name="sapxep-tuvungABC-tron-the"),

    path("flashcard/<int:flashcard_id>/study", views.study_theghinho, name="the-ghi-nho"),
    path("flashcard/<int:flashcard_id>/study/shuffle", views.study_shuffle, name="the-ghi-nho-tron-the"),
    path("flashcard/<int:flashcard_id>/quiz", views.study_quiz, name="quiz"),
    path("flashcard/<int:flashcard_id>/test", views.study_kiemtra, name="kiem-tra"),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flashcard/user/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "user"

urlpatterns = [
    path('profile/', views.profile_user, name='hoso'),
]

flashcard/templates/base.html
<!DOCTYPE html>
<html lang="vi">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    
    <!-- Fontawesome CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">
    <!-- Boxicons CSS -->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

    <!-- Bootstrap 5.2.3 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <!-- Icon web -->
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    <!-- Custom CSS -->
    {% block mycss %}{% endblock %}

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block header %}{% endblock %}
    {% block content %}{% endblock %}

    <!-- Import jQuery and Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.js"></script>
    <!-- Custom JS -->
    {% block myjs %}{% endblock %}
</body>
</html>

flashcard/templates/base_home.html
{% extends "base.html" %}

{% load static %}

{% block mycss %}
    <link rel="stylesheet" href="{% static 'study/trangchu/css/trangchu.css' %}">
    <link rel="stylesheet" href="{% static 'study/trangchu/css/userdropdown_trangchu.css' %}">
{% endblock %}

{% block header %}
    <header id="header" class="navbar navbar-expand-lg navbar-dark d-flex" role="navigation">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav col-4 align-items-center" style="padding-left: 20px;">
                <li class="nav-item">
                    <a href="{% url 'study:trangchu' %}"><img src={% static 'images/logo.svg' %} alt="logo" width="150" height="37"></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white mx-4" href="{% url 'study:trangchu' %}">Trang chủ</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white mx-4" href="{% url 'study:my-flashcard' %}">My FlashCard</a>
                </li>
            </ul>
            <div class="navbar-nav col-4 d-flex form-inputs mx-auto align-items-center">
                {% block searchfc %}
                    <form method="GET" action="{% url 'study:timkiem-flashcard' %}" class="search-container" style="width: 100%;">
                        <input class="form-control search-input" type="search" name="search_text" placeholder="Tìm kiếm FlashCard..." aria-label="Search">
                        <button type="submit" class="search-icon bx bx-search" style="border: none; background: none;"></button>
                    </form>
                {% endblock %}
            </div>
                       
            <ul class="navbar-nav align-items-center ml-auto">
                <li class="nav-item">
                    <button class="btn btn-outline-primary rounded-circle mx-2">
                        <i class="far fa-bell" style="color: white;"></i>
                    </button>
                </li>
                <li class="nav-item dropdown">
                    <button type="button" class="d-flex align-items-center mx-4" data-bs-toggle="dropdown"  aria-haspopup="true" aria-expanded="false" data-offset="0, 20"  style="background-color: #5c9bc2;border: 0;">    
                        <div class="profile-pic mr-3">
                            <img src="{{ user_login.avatar.url }}" alt="avatar">
                        </div>
                        <div class="profile-info">
                            <h3>{{user_login.username}}</h3>
                            <span>{{user_login.email}}</span>
                        </div>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end mx-4">
                        <a class="dropdown-item" href="{% url 'user:hoso' %}"> <span class=""></span>Hồ sơ</a>
                        <a class="dropdown-item" href="#"><span class=""></span>Cài đặt</a>
                        <a class="dropdown-item" href="{% url 'study:dangxuat' %}"><span class=""></span>Đăng xuất</a>
                    </ul>             
                </li>
            </ul>
        </div>
    </header>
{% endblock %}

{% block content %}{% endblock %}

{% block myjs %}{% endblock %}