flashcard/flashcard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("study.urls")),
    
    path("user/", include("user.urls")),

    path("admin/", admin.site.urls),
]

flashcard/study/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView

app_name = "study"

urlpatterns = [
    path("login/", views.Login_SignUpClass.as_view(), name="dangnhap"),
    path("", RedirectView.as_view(url='login/', permanent=True)),
    path("logout/", views.logout_view, name="dangxuat"),

    path("home/", views.trangchu, name="trangchu"),
    path("my-flashcard", views.my_flashcard, name="my-flashcard"),
    path("flashcards-search", views.search_flashcards, name="timkiem-flashcard"),
    path("my-flashcard/<int:flashcard_id>/add-cards", views.create_cards_for_flashcard, name="them-cards-flashcard"),
    path("my-flashcard/<int:flashcard_id>/edit", views.edit_flashcard, name="sua-flashcard"),
    path("my-flashcard/<int:flashcard_id>/edit-clone", views.edit_clone_flashcard, name="sua-clone-flashcard"),


    path("flashcard/<int:flashcard_id>/", views.study_flashcard_view, name="thenho"),
    path("flashcard/<int:flashcard_id>/shuffle", views.shuffle_card_show, name="tron-the"),

    path("flashcard/<int:flashcard_id>/sort-abc", views.sort_tuvung_ABC, name="sapxep-tuvungABC"),
    path("flashcard/<int:flashcard_id>/sort-abc/shuffle", views.shuffle_card_show_sort_ABC, name="sapxep-tuvungABC-tron-the"),

    path("flashcard/<int:flashcard_id>/study", views.study_theghinho, name="the-ghi-nho"),
    path("flashcard/<int:flashcard_id>/study/shuffle", views.study_shuffle, name="the-ghi-nho-tron-the"),
    path("flashcard/<int:flashcard_id>/quiz", views.study_quiz, name="quiz"),
    path("flashcard/<int:flashcard_id>/test", views.study_kiemtra, name="kiem-tra"),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flashcard/user/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "user"

urlpatterns = [
    path('profile/', views.profile_user, name='hoso'),
]

flashcard/study/models.py
from django.db import models
from user.models import LearnerUser
from django.core.exceptions import ValidationError
# Create your models here.
class FlashCard(models.Model):
    user = models.ForeignKey(LearnerUser, on_delete=models.CASCADE, related_name='user_flashcard')
    title = models.CharField(max_length=100)
    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)
    def __str__(self):
        return str(self.id) + ' - ' + self.title
    
    def clean(self):
        if not self.user_id:
            raise ValidationError('Please select a user before creating a new flash card.')
    
    def word_count(self):
        return self.card_set.count()
    
class Card(models.Model):
    word = models.CharField(max_length=100)
    meaning = models.CharField(max_length=200)
    flash_card = models.ForeignKey(FlashCard, on_delete=models.CASCADE)

    def clean(self):
        if not self.flash_card_id:
            raise ValidationError('Bạn phải lưu hoặc chọn một bộ thẻ trước khi tạo các từ vựng mới.')
        

flashcard/study/forms.py
from .models import LearnerUser, FlashCard, Card
from django import forms
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Tên người dùng'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email'}))
    password1 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={'placeholder': 'Mật khẩu'}))
    password2 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={'placeholder': 'Xác nhận mật khẩu'}))

    class Meta:
        model = LearnerUser
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].validators = []    

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and LearnerUser.objects.filter(email=email).exists():
            raise forms.ValidationError('Email này đã được sử dụng!!!')
        return email

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        if LearnerUser.objects.filter(email=email).exists():
            raise forms.ValidationError('Email này đã được sử dụng!!!')
        return cleaned_data

class CardForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = ['word', 'meaning', 'flash_card']
        widgets = {
            'word': forms.TextInput(attrs={'placeholder': 'Từ vựng'}),
            'meaning': forms.TextInput(attrs={'placeholder': 'Định nghĩa'}),
            'flash_card': forms.HiddenInput()
        }

    def __init__(self, *args, **kwargs):
        flash_card = kwargs.pop('flash_card', None)
        super(CardForm, self).__init__(*args, **kwargs)
        if flash_card:
            self.fields['flash_card'].initial = flash_card
            self.fields['flash_card'].queryset = FlashCard.objects.filter(id=flash_card.id)

CardFormSet = forms.inlineformset_factory(FlashCard, Card, form=CardForm, extra=2, can_delete=False)

class FlashCardForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Đặt tên cho bộ FlashCard của bạn', 'class': 'form-control mr-3'})
    )
    user = forms.ModelChoiceField(
        queryset=LearnerUser.objects.all(),
        widget=forms.HiddenInput(),
        empty_label=None
    )

    class Meta:
        model = FlashCard
        fields = ['title', 'user']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(FlashCardForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['user'].initial = user
            self.fields['user'].queryset = LearnerUser.objects.filter(id=user.id)

class FlashCardFormUpdate(forms.ModelForm):
    class Meta:
        model = FlashCard
        fields = ['title']  # Chỉ cho phép cập nhật tiêu đề

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].label = "New Title"  # Đặt nhãn cho trường tiêu đề

class CardUpdateForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = ['word', 'meaning']  # Chỉ cho phép cập nhật từ và nghĩa
        widgets = {
            'word': forms.TextInput(attrs={'placeholder': 'Từ vựng',
                                           'name': "card_data['word']",}),
            'meaning': forms.TextInput(attrs={'placeholder': 'Định nghĩa',
                                              'name': "card_data['meaning']",}),
        }

flashcard/study/views.py
import json
from django.shortcuts import render, redirect, get_object_or_404
from .models import FlashCard, Card
from django.contrib.auth import authenticate, login
from django.views.generic import View
from django.contrib import messages
from django.contrib.auth import logout
from .models import FlashCard
from .forms import SignUpForm, FlashCardForm, FlashCardFormUpdate, CardUpdateForm
from random import shuffle
from django.contrib.auth.decorators import login_required


def dangnhap(request):
    return render(request, 'study/dangnhap.html')

class Login_SignUpClass(View):
    def get(self, request):
        form_signup = SignUpForm()
        return render(request, 'study/dangnhap.html', {'form_signup': form_signup})
    def post(self, request):
        if 'username' in request.POST:
            form_signup = SignUpForm(request.POST)
            if form_signup.is_valid():
                user = form_signup.save()
                login(request, user)
                print("dang ky thanh cong")
                return redirect('user:hoso')
            else:
                form_signup = SignUpForm()
                print("dang ky khong thanh cong")
                request.POST = {}
                messages.error(request, 'Thông tin đăng ký không đúng', extra_tags='signup')
                return self.get(request)
        else:    
            email = request.POST.get('email')
            password = request.POST.get('password')
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                print("dang nhap thanh cong")
                return trangchu(request)
            else:
                print("dang nhap khong thanh cong")
                request.POST = {}
                messages.error(request, 'Địa chỉ email hoặc mật khẩu không đúng', extra_tags='login')
                return self.get(request)



def trangchu(request):
    if request.user.is_authenticated:
        print("da dang nhap")
        flashcard_recent = FlashCard.objects.all().order_by('-time_update')[:12]
        context = {'flashcard_data_recent': flashcard_recent, 'user_login': request.user}
    else:
        print("chua dang nhap")
        context = {'user_login': None, 'flashcard_data_recent': None}
    
    return render(request, 'study/trangchu.html', context)

def logout_view(request):
    logout(request)
    return redirect('study:dangnhap')

def study_flashcard_view(request, flashcard_id):
    flashcard = get_object_or_404(FlashCard, id=flashcard_id)
    cards = flashcard.card_set.all()
    context = {
        'flashcard': flashcard,
        'cards': cards,
        'user_login': request.user,
        'cards_order': cards,
        'isSortABC': False,
        'isShuffle': False
    }
    return render(request, 'study/flashcard.html', context)

def sort_flashcard(request, sort):
    if sort == 'alphabet':
        flashcard = FlashCard.objects.order_by('title')
    elif sort == 'newest':
        flashcard = FlashCard.objects.order_by('-created_at')
    elif sort == 'oldest':
        flashcard = FlashCard.objects.order_by('created_at')
    else:
        flashcard = FlashCard.objects.all()
    context = {'flashcard_data': flashcard, 'user_login': request.user}
    return render(request, 'study/trangchu.html', context)

def sort_tuvung_ABC(request, flashcard_id):
    flashcard = get_object_or_404(FlashCard, id=flashcard_id)
    cards = flashcard.card_set.all()
    cards_order = flashcard.card_set.order_by('word')
    context = {
        'flashcard': flashcard,
        'cards': cards,
        'user_login': request.user,
        'cards_order': cards_order,
        'isSortABC': True,
        'isShuffle': False
    }
    return render(request, 'study/flashcard.html', context)

def shuffle_card_show(request, flashcard_id):
    flashcard = get_object_or_404(FlashCard, id=flashcard_id)
    cards = flashcard.card_set.all()
    cards_list = list(cards)
    shuffle(cards_list)
    context = {
        'flashcard': flashcard,
        'cards': cards_list,
        'user_login': request.user,
        'cards_order': cards,
        'isSortABC': False,
        'isShuffle': True
    } 
    
    return render(request, 'study/flashcard.html', context)

def shuffle_card_show_sort_ABC(request, flashcard_id):
    flashcard = get_object_or_404(FlashCard, id=flashcard_id)
    cards = flashcard.card_set.all()
    cards_order = flashcard.card_set.order_by('word')
    cards_list = list(cards)
    shuffle(cards_list)
    context = {
        'flashcard': flashcard,
        'cards': cards_list,
        'user_login': request.user,
        'cards_order': cards_order,
        'isSortABC': True,
        'isShuffle': True
    } 
    
    return render(request, 'study/flashcard.html', context)

def study_theghinho(request, flashcard_id):
    flashcard = get_object_or_404(FlashCard, id=flashcard_id)
    cards = flashcard.card_set.all()
    context = {
        'flashcard': flashcard,
        'cards': cards,
        'user_login': request.user,
    } 
    return render(request, 'study/mode/mode_study.html', context)

import random
def study_quiz(request, flashcard_id):
    flashcard = get_object_or_404(FlashCard, id=flashcard_id)
    cards_quiz = flashcard.card_set.all().order_by('?')[:10]

    question_ids = [card.id for card in cards_quiz]
    other_cards = Card.objects.filter(flash_card=flashcard).exclude(id__in=question_ids)
    questions = []
    for card in cards_quiz:
        question = {
            'word': card.word,
            'answers': [card.meaning],
            'correct_answer_index': 0
        }
        if len(other_cards) >= 3:
            # Lấy ngẫu nhiên 3 đáp án khác từ danh sách other_cards
            three_other_cards = random.sample(list(other_cards), 3)
            question['answers'].extend([other_answer.meaning for other_answer in three_other_cards])
        else:
            # Nếu số lượng other_cards không đủ, lấy tất cả các đáp án khác từ danh sách other_cards
            question['answers'].extend([other_card.meaning for other_card in other_cards])

        # Xáo trộn thứ tự của các đáp án
        random.shuffle(question['answers'])

        # Update correct_answer_index based on shuffled answers
        question['correct_answer_index'] = question['answers'].index(card.meaning)

        # Lưu câu hỏi vào danh sách các câu hỏi
        questions.append(question)
    context = {
        'flashcard': flashcard,
        'user_login': request.user,
        'questions': questions,
    } 
    return render(request, 'study/mode/mode_quiz.html', context)

def study_kiemtra(request, flashcard_id):
    flashcard = get_object_or_404(FlashCard, id=flashcard_id)
    cards_test_yesno = flashcard.card_set.all().order_by('?')[:10]
    question_yesno_ids = [card.id for card in cards_test_yesno]
    cards_test_quiz = Card.objects.filter(flash_card=flashcard).exclude(id__in=question_yesno_ids).order_by('?')[:10]
    
    question_ids = question_yesno_ids + [card.id for card in cards_test_quiz]
    other_cards = Card.objects.filter(flash_card=flashcard).exclude(id__in=question_ids)
    questions_yesno = []
    questions_quiz = []

    
    for card in cards_test_yesno:
        other_card_yn = random.sample(list(other_cards), 1)[0]
        stat_queston = random.choice(["yes", "no"])
        if stat_queston == "no":
            question = {
                'word': card.word,
                'meaning': other_card_yn.meaning,
                'correct_answer': 'no',
            }            
            questions_yesno.append(question)
        else:
            question = {
                'word': card.word,
                'meaning': card.meaning,
                'correct_answer': 'yes',
            }
            questions_yesno.append(question)
    
    for card in cards_test_quiz:
        question = {
            'word': card.word,
            'answers': [card.meaning],
            'correct_answer_index': 0
        }
        if len(other_cards) >= 3:
            # Lấy ngẫu nhiên 3 đáp án khác từ danh sách other_cards
            three_other_cards = random.sample(list(other_cards), 3)
            question['answers'].extend([other_answer.meaning for other_answer in three_other_cards])
        else:
            # Nếu số lượng other_cards không đủ, lấy tất cả các đáp án khác từ danh sách other_cards
            question['answers'].extend([other_card.meaning for other_card in other_cards])

        # Xáo trộn thứ tự của các đáp án
        random.shuffle(question['answers'])

        # Update correct_answer_index based on shuffled answers
        question['correct_answer_index'] = question['answers'].index(card.meaning)
        
        # Lưu câu hỏi vào danh sách các câu hỏi
        questions_quiz.append(question)


    context = {
        'flashcard': flashcard,
        'user_login': request.user,
        'questions_yesno': questions_yesno,
        'questions_quiz': questions_quiz,
    } 
    return render(request, 'study/mode/mode_test.html', context)

def study_shuffle(request, flashcard_id):
    flashcard = get_object_or_404(FlashCard, id=flashcard_id)
    cards = flashcard.card_set.all()
    cards_list = list(cards)
    shuffle(cards_list)
    context = {
        'flashcard': flashcard,
        'cards': cards_list,
        'user_login': request.user,
        'isShuffle': True
    } 
    return render(request, 'study/mode/mode_study.html', context)

def my_flashcard(request):
    user_flashcards = FlashCard.objects.filter(user=request.user)
    if request.method == 'POST':
        flashcard_form = FlashCardForm(request.POST, user=request.user)
        if flashcard_form.is_valid():
            flashcard = flashcard_form.save(commit=False)
            flashcard.user = request.user  # Gán người dùng hiện tại cho trường user
            flashcard.save()
            return redirect('study:them-cards-flashcard', flashcard_id=flashcard.id)
    else:

flashcard/templates/study/flashcard.html
{% extends "base_home.html" %}
{% load static %}

{% block mycss %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'study/flashcard_detail/css/flashcard.css' %}">
    <style>
        .popup-container {
            position: relative;
          }
          
          .popup-description {
            display: none;
            position: absolute;
            top: 100%;
            left: 0;
            background-color: cornflowerblue;
            padding: 5px;
            border: 1px solid #ccc;
            border-radius: 5px;
          }
          
          .popup-container:hover .popup-description {
            display: block;
          }
    </style>
{% endblock %}

{% block title%}Flash card{% endblock %}

{% block content %}
    <main class="FlashcardShow" style="margin-top: 3.75rem;">
        <div class="FlashcardTitle d-flex flex-row justify-content-between">
            <h1>{{ flashcard.title }}</h1>
        </div>
        <div class="ModeLearningSec">
            <ul class="ModeLearningList">
                <a href="{% url 'study:the-ghi-nho' flashcard_id=flashcard.id %}" class="ModeLearningItem">
                    <i class='bx bx-note'></i><div class="ModeLearningItemHeader">
                        <h2 class="ModeLearningItemName">Thẻ ghi nhớ</h2>
                    </div>
                </a>
                <a href="{% url 'study:quiz' flashcard_id=flashcard.id %}" class="ModeLearningItem">
                    <i class="far fa-question-circle"></i><div class="ModeLearningItemHeader">
                        <h2 class="ModeLearningItemName">Quiz</h2>
                    </div>
                </a>
                <a href="{% url 'study:kiem-tra' flashcard_id=flashcard.id %}" class="ModeLearningItem">
                    <i class="fas fa-scroll"></i><div class="ModeLearningItemHeader">
                        <h2 class="ModeLearningItemName">Kiểm tra</h2>
                    </div>
                </a>
            </ul>     
        </div>
        <div class="Flashcard-studyPreview d-flex">
            <div id="flashcard-carousel" class="carousel slide">
                <div class="carousel-inner">
                    {% for card in cards %}
                    <div class="carousel-item{% if forloop.first %} active{% endif %}">
                        <div class="flip-card shadow-sm" style="height: 450px;"> 
                            <div class="face front">
                                <div style="width: 70%;">
                                    <h3>{{ card.word }}</h3>
                                </div>
                            </div>
                            <div class="face back">
                                <div style="width: 70%;">
                                    <h3>{{ card.meaning }}</h3>                        
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>
                    
                <a class="carousel-control-prev" style="background-color: #b7d9db" href="#flashcard-carousel" role="button" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon bg-red" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </a>
                <a class="carousel-control-next" style="background-color: #b7d9db" href="#flashcard-carousel" role="button" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true" ></span>
                    <span class="visually-hidden">Next</span>
                </a>
            </div>
            <div class="underStudyPreview">
                <div class="d-flex gap-3" style="padding-top: 0.5rem;">
                    {% if isSortABC %}
                        {% if isShuffle %}
                            <a href="{% url 'study:sapxep-tuvungABC' flashcard_id=flashcard.id %}" type="button" id="btn-mix-card"><i class="fas fa-sync-alt fa-2x"></i></a>
                        {% else %}
                            <a href="{% url 'study:sapxep-tuvungABC-tron-the' flashcard_id=flashcard.id %}" type="button" id="btn-mix-card"><i class="fas fa-sync-alt fa-2x"></i></a>
                        {% endif %}
                    {% elif isShuffle %}
                        <a href="{% url 'study:thenho' flashcard_id=flashcard.id %}" type="button" id="btn-mix-card"><i class="fas fa-sync-alt fa-2x"></i></a>
                    {% else %}
                        <a href="{% url 'study:tron-the' flashcard_id=flashcard.id %}" type="button" id="btn-mix-card"><i class="fas fa-sync-alt fa-2x"></i></a>
                    {% endif %}
                    <span id="describe-btn-mix">Trộn thẻ đang TẮT</span>
                    
                </div>
                <div class="d-flex gap-3" style="padding-top: 0.5rem;">
                    <button class="fas fa-cog fa-2x" type="button" id="setting-card-show"></button>
                    <a href="{% url 'study:the-ghi-nho' flashcard_id=flashcard.id %}" class="fas fa-expand fa-2x" type="button" id="all-screen"></a>  
                </div>
            </div>   
        </div>

        
        <div class="FlashcardInfo">
            <div class="ContentInfo d-flex flex-wrap justify-content-between position-relative">
                <div class="UserInfoFlashcard">
                    <div class="profile-pic">
                        <img src="{{ flashcard.user.avatar.url }}" alt="avatar">
                    </div>
                    <div class="profile-info">
                        <span>Tạo bởi</span>
                        <h4>{{flashcard.user.email}}</h4>
                    </div>
                </div>
                <div class="OptionFlashcard">
                    <div type="button" id="toggle-heart"><i class="far fa-heart text-danger fa-2x"></i></div>
                    <div class="popup-container">
                        {% if user_login == flashcard.user%}
                        <a href="{% url 'study:sua-flashcard' flashcard_id=flashcard.id %}" type="button" class="popup-button button-option-circle" style="text-decoration: none;">   
                        {% else %}
                        <a href="{% url 'study:sua-clone-flashcard' flashcard_id=flashcard.id %}" type="button" class="popup-button button-option-circle" style="text-decoration: none;">
                        {% endif %}    
                            <i class="fas fa-pen"></i>
                        </a>
                        <div class="popup-description">
                            {% if user_login == flashcard.user%}
                                Sửa
                            {% else %}
                                Sao chép và sửa 
                            {% endif %}
                        </div>        
                    </div>
                    <button class="button-option-circle"><i class="fas fa-ellipsis-h"></i></button>
                </div>
            </div>
        </div>
        <div class="ListCard">
            <section class="ListCardSec">
                <div class="ListCardHeader">
                    <span style="font-weight: 700;font-size: 1.25rem;margin-bottom: 0.5rem;">
                        Thuật ngữ trong học phần này ({{ flashcard.word_count }})
                    </span>
                    <div class="header-control">
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownSort" data-bs-toggle="dropdown" aria-expanded="false">
                                Thứ tự gốc
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'study:thenho' flashcard_id=flashcard.id %}" class="dropdown-item" id="sort-origin">Thứ tự gốc</a></li>
                                <li><a href="{% url 'study:sapxep-tuvungABC' flashcard_id=flashcard.id %}" class="dropdown-item" id="sort-ABC" href>Bảng chữ cái</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <section class="DScacthuatngu" id='ds-thuat-ngu'>
                    {% for card in cards_order %}
                        <div class="ThuatNgu" aria-label="Thuật ngữ">
                            <div class="ThuatNguinner">
                                <div class="contentWrapper">
                                    <div class="ThuatNgu-content">
                                        <div class="ThuatNgu-side" style="width: 50%;">
                                            <div class="ThuatNgu-sideContent">
                                                <span style="color: #1a1d28;word-wrap: break-word;">
                                                    {{ card.word }}
                                                </span>
                                            </div>
                                        </div>
                                        <div class="ThuatNgu-side" style="width: 50%;position: relative;">
                                            <div class="ThuatNgu-sideContent">
                                                <span style="color: #1a1d28;
                                                    display: block;
                                                    word-wrap: break-word;
                                                    font-family: Lucida Grande,Arial,sans-serif!important;">
                                                    {{ card.meaning }}  
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    
                                </div>
                                <button type="button" id="toggle-star" style="border: none;background: none;">
                                    <i class="fas fa-star"  style="padding-left: 32px;"></i>
                                </button>
                            </div>
                        </div>
                    {% endfor %}
                </section>
            </section>
        </div>
    </main>
{% endblock %}
{% block myjs %}
    {{ block.super }}
    <script src="{% static 'study/flashcard_detail/js/flashcard.js' %}"></script>     
{% endblock myjs %}

flashcard/templates/study/navbar_study.html
{% extends "base.html" %}

{% load static %}

{% block mycss %}
    <link rel="stylesheet" href="{% static 'study/trangchu/css/trangchu.css' %}">
    <link rel="stylesheet" href="{% static 'study/flashcard_detail/css/flashcard.css' %}">
    <style>
        .navStudy a.ModeLearningItem{
            width: 160px;
            height: 3.75rem;
            border: none;
            background: none;
            margin-right: 0;
        }
        .navStudy a.ModeLearningItem:hover{
            background-color: #939bb459;
        }
        .navStudy a.btn-exit {
            width: 40px;
            height: 40px;
            border: 1px solid #111;
            background: none;
            cursor: pointer;
            border-radius: 20%;
            text-align: center;
            line-height: 35px;
            color: black;
        }
    </style>
{% endblock %}

{% block header %}
    <header id="header" class="navbar navbar-expand-lg navbar-dark d-flex" role="navigation">
        <div class="collapse navbar-collapse" id="navbarNav">
            <div class="navbar-nav col-4 align-items-center navStudy">
                <div class="nav-item">
                    <div class="btn-group" style="margin-left: 20px;">
                        <a href="{% url 'study:the-ghi-nho' flashcard_id=flashcard.id %}" class="ModeLearningItem">
                            <i class='bx bx-note'></i>
                            <div class="ModeLearningItemHeader">
                                <h2 id="modeName" class="ModeLearningItemName">Thẻ ghi nhớ</h2>
                            </div>
                        </a>
                        <button id="dropdownMode" class="btn btn-lg btn-secondary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false"></button>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'study:the-ghi-nho' flashcard_id=flashcard.id %}" class="dropdown-item">Thẻ ghi nhớ</a></li>
                            <li><a href="{% url 'study:quiz' flashcard_id=flashcard.id %}" class="dropdown-item">Quiz</a></li>
                            <li><a href="{% url 'study:kiem-tra' flashcard_id=flashcard.id %}" class="dropdown-item" href>Kiểm tra</a></li>
                        </ul> 
                    </div>
                </div>
            </div>
            {% block navbar_title %}
            <div id="navbar-count-card" class="navbar-nav navStudy col-4 mx-auto" style="flex-direction: column;">
                <h4 id="card-counter-id">1/{{flashcard.word_count}}</h4>
                <span>{{flashcard.title}}</span>
            </div>
            {% endblock %}
            <div class="navbar-nav navStudy align-items-center ml-auto m-3">
                <a href="{% url 'study:thenho' flashcard_id=flashcard.id %}" class="btn-exit"><i class="fas fa-times"></i></a>
            </div>
        </div>
    </header>
{% endblock %}

{% block content %}
    

{% endblock %}

{% block myjs %}
    <script>

        // Lấy phần tử dropdown-toggle
        const dropdownModeName = document.querySelector('#modeName');

        // Lấy danh sách các phần tử dropdown-item
        const dropdownItems = document.querySelectorAll('.dropdown-item');

        // Lắng nghe sự kiện click trên mỗi phần tử dropdown-item
        dropdownItems.forEach(function(item) {
            item.addEventListener('click', function(event) {
                // Lấy nội dung của mục được chọn
                var selectedModeItem = this.textContent;
                // Thay đổi nội dung của dropdown-toggle thành nội dung của dropdown-item được click
                dropdownModeName.textContent = selectedModeItem;
                // Lưu trữ tên của nút được chọn trong localStorage
                localStorage.setItem('selectedItemModeName', selectedModeItem);
            });
        });

        var selectedItemModeName = localStorage.getItem('selectedItemModeName');
        if (selectedItemModeName) {
            dropdownModeName.textContent = selectedItemModeName;
        }
    </script>
{% endblock %}